### ISSUE TITLE
Problem CONTAO-Theme-Convert-Installation

### ISSUE THREAD

**Issue by Miket2020** [contao-themes-net/convert-theme-bundle#1]
contao-themes-net/convert-theme-bundle

Hallo!
Bei der CONTAO-Theme-Installation (CONVERT) via CONTAO-Manager1.2.5 erfolgt ein Abbruch mit Fehler "Cannot allocate memory".
Selbes auch bei Test-Installation von MATE.
Es wurde, wie empfohlen ein neues CONTAO4.9.3 CMS "frisch" ohne vorige Templates neu installiert.

1. Wie/wo kann ich das Theme Bundle als Datei downloaden, um im CONTAO-Backend direkt zu installieren.

2. Wo müssen/können evtl. Einstellungsänderungen (Speichereinschränkung) im CONTAO-Backend eingestellt werden?

Gruß
Thiele 

> FEHLERMELDUNG:
$ /usr/bin/php7.4-cli -q -d memory_limit=-1 /homepages/0/d799030550/htdocs/CONTAO4-9-Fondsfinder/web/contao-manager.phar.php composer require contao-themes-net/convert-theme-bundle --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

# Process terminated with exit code 255
# Result: Unknown error

---

### The background task has stopped unexpectedly ###

**Comment by seibtph** [comment]
Verwendest du die Composer Resolver Cloud? Das kann im Contao Manager unter Serverkonfiguration aktiviert werden.

**Comment by Miket2020** [comment]
Serverkonfiguration finde ich nicht.
Unter "Systemwartung" finde ich nur:
Composer Dependencies, Composer-Cache, Composer Class Loader?

**Comment by Miket2020** [comment]
Inzwischen Composer Resolver Cloud gefunden, war aktiviert.
Jetzt hab ichs deaktiviert. Auch dann kommt der selbe Fehler/Abbruch.
Server Configuration: 1&1 IONOS SE
Was muss ich bei Configuration: Other
manuell in Custom Configuration-PHPBinary eingeben?

**Comment by seibtph** [comment]
Was für ein Hosting Paket nutzt du denn? Vielleicht ist das ja nicht geeignet für Contao.

Bei Server Configuration sollte 1&1 IONOS SE ausgewählt sein, das passt also.
