### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dlGAfrica** [contao-themes-net/convert-theme-bundle#11]
Hallo,
ich habe versucht, über den Contao-Manager und das Install-Tool das Theme/Template Convert und/oder 0.1 zu installieren.
Das klappt bis zu dem Moment, in dem ich dem Installt-Tool sage "Ein Template importieren".
Dann erhalte ich jedesmal die Fehlermeldung 
"Der Import konnte nicht abgeschlossen werden! Ist die Datenbank aktuell und die Template-Datei kompatibel mit Ihrer Contao-Version?
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
Kann mir Jemand helfen?

**Comment by MDevster** [comment]
Du müsstest die Datenbank wieder komplett leeren oder eine neue Datenbank auswählen bevor du einen weiteren Theme probierst.

**Comment by MDevster** [comment]
Konntest du das Problem lösen? Du kannst das Ticket gern erneut öffnen solltest du noch Hilfe benötigen.

**Comment by dlGAfrica** [comment]
Hallo Mathias,
ja, ich habe die Datenbank nicht nur komplett geleert, sondern gelöscht und eine neue Datenbank angelegt (mehrmals), leider immer ohne Erfolg.
Ich habe den Verdacht, dass bei der Aktualisierung der Datenbank Felder entweder nicht, oder falsch angelegt werden.
Ich habe jetzt open sauce von Rocksolid mit Hilfe der cto-Datei installiert. das hat einwandfrei funktioniert.
Vielen Dank trotzdem und viele Grüße
Georg

**Comment by MDevster** [comment]
Hallo Georg, kannst du mir bitte noch Informationen zu deinem Setup zusenden? Zum Beispiel PHP Version, Hoster, Webhosting-Paket, damit wir das noch einmal prüfen und das Problem möglicherweise beheben können? Gern auch per E-Mail an support [ at ] pdir.de

**Comment by dlGAfrica** [comment]
Hallo Mathias,
mein Hoster ist alfahosting, PHP-Versionen 4.4, 5.2-5.6, 7.0-7.4, 8.0, PERL-Version 5.20, MySQL-Version 5.7
mein Hosting-Paket ist Multi XL (SSD)
Eigentlich hatte ich mit denen bisher keine Probleme, erst mit der aktuellen Contao-Version 4.X lief der Contao-Manager nicht mehr, wenn ich versucht habe, Contao mit dem Tool von alfahosting zu installieren. Ich habe die Installation dann mit Hilfe der youtube-Anleitung von Christian Feneberg gamacht. Das ist super einfach, klar verständlich und nachvollziehbar, auch für quasi Laien, wie mich.
