### ISSUE TITLE
Wrong image path within CONVERT Theme Setup

### ISSUE THREAD

**Issue by SunBlack** [contao-themes-net/convert-theme-bundle#12]
Just tried this theme now an ´d saw an missing image within `CONVERT Theme Setup`

![image](https://user-images.githubusercontent.com/483922/153097596-f14b3be9-3425-4bc2-bb88-5b382ebd40ff.png)

Reason is here (missing file extension `.svg`)
https://github.com/contao-themes-net/convert-theme-bundle/blob/bb50826f55ca57f0a153b91abf446bfac9bb0f53/src/Resources/contao/templates/be/be_converttheme_setup.html5#L8

**Comment by seibtph** [comment]
fixed in version 1.7.0
