### ISSUE TITLE
Demo Bilder werden nach Installation nicht angezeigt

### ISSUE THREAD

**Issue by bewerbungsmatrix** [contao-themes-net/convert-theme-bundle#17]
Verwende Contao 4.13.14 mit PHP 8.0
Nach der Installation der minimal_installtool.sql und alle Ausführungen die in den Installationsschritten angegeben werden, erscheint auf der Website zwar der Text, aber die passenden Bilder erscheinen nicht dazu.
Weiter unter dem Punkt Themes/Konfiguration kann der Ordner der der Bildschirmfotos nicht ausgewählt werden.
Sollte dies ein Hinweis für die Fehlersuche sein.
Datenbank wurde schon mal gelöscht und neu durchgeführt, Ergebnis bleibt gleich.
Unter Punkt Themes/Konfiguration / Templates Ordner kann man auch nichts festlegen, dort befindet sich nur ein Strich
danke für die Hilfe
lg MArco

**Comment by seibtph** [comment]
Hallo Marco,

vielleicht hilft dir einer der folgenden Punkte:

- hast du unter Systemwartung die Symlinks neu erstellt?
- ist der Ordner convert in der Dateiverwaltung angelegt und ist er öffentlich?
- sind die Bilder bei den Inhaltselementen ausgewählt oder fehlen die Bildverknüpfungen?

Ich habe den Import der Demo auch nochmal getestet und konnte da keine Fehler feststellen.

**Comment by bewerbungsmatrix** [comment]
Hallo Philipp, danke für deine Unterstützung!

    hast du unter Systemwartung die Symlinks neu erstellt? **Ja habe ich, bin genau nach der Beschreibung vorgegangen.**
    ist der Ordner convert in der Dateiverwaltung angelegt und ist er öffentlich? **Ja ist sie.**
    sind die Bilder bei den Inhaltselementen ausgewählt oder fehlen die Bildverknüpfungen? **Nein leider, sie fehlen**

Ich habe dir einige Bilder per Mail gesendet, vielleicht hilft es.
danke lg

**Comment by bewerbungsmatrix** [comment]
Hallo Ihr lieben, habe kleine Version 2 Mal neu installiert, kein Unterschied.
Habe mich entschlossen das GROßE Packet zu installieren und es funkt jetzt.
Ihr könnt das Ticket schließen, danke
