### ISSUE TITLE
_custom_variables & custom scss reagiert nicht

### ISSUE THREAD

**Issue by bewerbungsmatrix** [contao-themes-net/convert-theme-bundle#18]
Hallo liebes Team, leider muss ich wieder ein Ticket öffnen!
Contao Version 4.13.14
PHP Version 8.1

Leider reagiert weder der _custom_variables & custom scss.
auch nicht mit cach löschen. Alles bleibt beim alten.
//@import '#{$scssPath}/colour_schemes/dark_mode';

Habt Ihr einen Tipp für mich? Braucht ihr einen Zugang?
Danke lg

**Comment by seibtph** [comment]
Hast du die Datei im Contao-Editor bearbeitet oder per FTP? Bei letzterem muss auch noch der Skriptcache unter Systemwartung geleert werden.

**Comment by bewerbungsmatrix** [comment]
Direkt über Contao Editor.

**Comment by seibtph** [comment]
Wenn das Problem noch besteht kannst du uns gern mal einen Contao Zugang an _support [AT] pdir . de_ senden. 

Du hast die Ordner in der Dateiverwaltung auch nicht umbenannt? Das ist auch schon ein paar mal der Grund gewesen.

**Comment by MDevster** [comment]
This issue has been closed manually due to inactivity. Please reopen it if this is still relevant.

--

Dieses Problem wurde aufgrund von Inaktivität manuell geschlossen. Bitte öffne es erneut, falls dies noch relevant ist.
