### ISSUE TITLE
Button für Kontaktformular wird nicht passend gestylt

### ISSUE THREAD

**Issue by joehi** [contao-themes-net/convert-theme-bundle#2]
Wenn man eine eigene Seite für das Kontaktformular anlegt, wird der Button für das Absenden des Kontaktformulars nicht gestylt.

Auf der Demo auf der Seite Style-Guide wird der Button nur passend gestylt, solange mindestens ein weiterer Button vom Elementtyp Hyperlink auf der Seite vorhanden ist.

Zum Nachvollziehen einfach auf der Seite Style-Guide den Artikel "Texte / Buttons" einmal deaktivieren.

**Comment by seibtph** [comment]
Sollte jetzt mit Version 1.3.4 gefixt sein.
