### ISSUE TITLE
Pflichtfelder im Formular werden in orange und nicht in selbst definierten Farben umrandet

### ISSUE THREAD

**Issue by joehi** [contao-themes-net/convert-theme-bundle#3]
Wenn im Formular ein Feld als Pflichtfeld definiert ist, wird der Rahmen um das Feld in orange eingefärbt, obwohl die Farben für das Theme in der Datei _custom_variables.scss neu definiert wurden.
Anscheinend fehlt hier noch eine Definition bei den Farbdefinitionen in der Datei _custom_variables.scss.

**Comment by seibtph** [comment]
Du kannst dafür die Variable `$error-color` nutzen. Also diese einfach noch in der _custom_variables.scss mit aufnehmen, z. B.:

`$error-color: #000;`

**Comment by joehi** [comment]
Mit der Variable $error-color ändern sich dann aber gleichzeitig auch die Farben des Hintergrund (.bg-error) sowie des Button [.btn.btn-error].
Ich möchte jedoch nur die Rahmen-Farbe des Pflichtfeldes bei den Formularen anpassen.

**Comment by seibtph** [comment]
Du kannst auch folgende CSS-Anweisung in der custom.scss einfügen, dann wird nur der Rahmen des Eingabefeldes angepasst:

```
.ce_form .widget:not(.widget-checkbox):not(.widget-radio) input:not(:placeholder-shown):invalid {
  border-color: #8c8c8c;
}
```

**Comment by joehi** [comment]
Vielen Dank für den Hinweis.
