### ISSUE TITLE
Favicon lässt sich nicht ändern

### ISSUE THREAD

**Issue by joehi** [contao-themes-net/convert-theme-bundle#4]
Nach Installation des Convert-Theme in Contao 4.9.x habe ich anfangs das Favicon im Website Root auf das mit dem Theme mitgelieferte Icon gesetzt. Das hat auch funktioniert.
Eine Änderung des Favicon auf ein eigenes Icon funktioniert jedoch nicht. Im Backend wird das korrekte Favicon ausgeliefert, im Frontend wird jedoch fälschlicherweise weiterhin das vom Convert-Theme mitgelieferte Favicon ausgeliefert.
Dafür verantwortlich ist vermutlich folgender Eintrag in der head-Section der Frondend-Seite:
`<link rel="shortcut icon" href="files/convert/img/favicon.ico" type="image/x-icon"/>`
Hier steht die falsche URL drin, sie wird bei Änderungen nicht angepasst.

**Comment by seibtph** [comment]
Du kannst Template fe_page_convert.html5 anpassen und die entsprechende Zeile (Zeile 21 müsste es sein) entfernen, dann wird auch das richtige Favicon gesetzt. Das werden wir in der nächsten Version anpassen.
