### ISSUE TITLE
Button "Eigene Landingpage erstellen" nicht zentrierbar

### ISSUE THREAD

**Issue by AgentCT** [contao-themes-net/convert-theme-bundle#6]
Hallo,

der Button "Eigene Landingpage erstellen" ist nicht zentrierbar, egal wie man ihn formatiert.

Es wäre schöner wenn man diesen zentrieren könnte, so wie man es über dem Text über dem Trennstrich mache kann.

Vielen Dank

**Comment by seibtph** [comment]
Du kannst bei dem Teaserbox-Element unten bei _Erweiterte CSS-Klassen - Klassen für Inhaltselemente - Textausrichtung_ **text-center** auswählen, dann wird alles mittig dargestellt.

Wenn du nur den Button zentriert haben möchtest, könntest du das über eine Anpassung in der custom.scss machen:

```
.intro .ce_ct_teaserBox .pageLink {
    text-align: center;
}
```
