### ISSUE TITLE
Unschärfe Intro Bild

### ISSUE THREAD

**Issue by sophie1702** [contao-themes-net/convert-theme-bundle#7]
Hallo,
Das Intro Bild hat bei mir immer eine gewisse Unschärfe, kann ich die irgendwie von dem Bild entfernen?

**Comment by seibtph** [comment]
Hallo @sophie1702,

du kannst das mittels CSS in der custom.scss lösen:

```
.intro .ce_ct_teaserBox .image>div {
    filter: none;
}
```

Danach die Seite mit Strg + F5 neuladen bzw. könnte es auch nötig sein den Skriptcache zu leeren.
